name: DAST Scan

on:
  workflow_run:
    workflows: ["Deploy to AWS EC2"]
    types:
      - completed

jobs:
  dast_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Ensures full repo is checked out

      # Set up Docker
      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      # Docker login to pull ZAP image from Docker Hub
      - name: Docker login
        run: echo "${{ secrets.DOCKER_HUB_PASS }}" | docker login -u "tintwaiyanmin97" --password-stdin

      # Debug: Check if the script exists
      - name: Debug - List Files
        run: ls -l scripts

      # Ensure script has correct permissions
      - name: Make zap-script.sh Executable
        run: chmod +x scripts/zap-script.sh

      # Run the OWASP ZAP scan
      - name: Run OWASP ZAP Scan
        env:
          EC2_HOST: "13.212.9.188"
        run: ./scripts/zap-script.sh  # Execute the script

      # Upload the ZAP report
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: ./zap_baseline_report.html
